services:
  - type: web
    name: pamel-network
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: pamel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: pamel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: pamel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: pamel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: pamel-db
          property: password

databases:
  - name: pamel-db
    databaseName: pamel
    user: pamel_user
    plan: free
